https://numpy.org/doc/stable/user/quickstart.html

####Basic numpy 

In [ ]:
####Numpy basic 
import numpy as np
>>> a = np.arange(15).reshape(3, 5)

>>> a.shape

>>> a.ndim

>>> a.dtype.name
>>> a.itemsize

>>> a.size

>>> type(a)
<class 'numpy.ndarray'>
>>> b = np.array([6, 7, 8])
>>> b

>>> type(b)
<class 'numpy.ndarray'>

In [ ]:
###Numpy Arrey creation
import numpy as np
>>> a = np.array([2, 3, 4])
>>> a

>>> a.dtype

>>> b = np.array([1.2, 3.5, 5.1])
>>> b.dtype



In [ ]:
a = np.array(1, 2, 3, 4)    # WRONG
Traceback (most recent call last):
  ...
TypeError: array() takes from 1 to 2 positional arguments but 4 were given
>>> a = np.array([1, 2, 3, 4])  # RIGHT

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
>>> b


In [ ]:
c = np.array([[1, 2], [3, 4]], dtype=complex) 
#complex is when you have number and letters
>>> c


In [ ]:
>>> np.zeros((3, 4))
>>> np.ones((2, 3, 4), dtype=np.int16)
>>> np.empty((2, 3)) 

In [ ]:
>>>np.arange(10, 30, 5)

>>> np.arange(0, 2, 0.3)  # it accepts float arguments


In [ ]:
from numpy import pi
>>> np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
>>> x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
>>> f = np.sin(x)

####Printing Arrays

In [2]:
>>>a = np.arange(6) # 1d array
>>> print(a)

>>> b = np.arange(12).reshape(4, 3) # 2d array
>>> print(b)

>>> c = np.arange(24).reshape(2, 3, 4)  #3d array
>>> print(c)


SyntaxError: invalid syntax (256028609.py, line 1)

In [ ]:
>>>print(np.arange(10000))

>>> print(np.arange(10000).reshape(100, 100))


In [ ]:
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

In [ ]:
###Basic Operations

In [ ]:
a = np.array([20, 30, 40, 50])
>>> b = np.arange(4)
>>> b

>>> c = a - b
>>> c

>>> b**2

>>> 10 * np.sin(a)

>>> a < 35


In [ ]:
A = np.array([[1, 1],

>>> B = np.array([[2, 0],

>>> A * B     # elementwise product

>>> A @ B     # matrix product

>>> A.dot(B)  # another matrix product


In [ ]:
>>> rg = np.random.default_rng(1)  # create instance of default random number generator
>>> a = np.ones((2, 3), dtype=int)
>>> b = rg.random((2, 3))
>>> a *= 3
>>> a

>>> b += a
>>> b
>>> a += b  # b is not automatically converted to integer type
Traceback (most recent call last):
    ...
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
>>>a = np.ones(3, dtype=np.int32)
>>> b = np.linspace(0, pi, 3)
>>> b.dtype.name

>>> c = a + b
>>> c

>>> c.dtype.name

>>> d = np.exp(c * 1j)
>>> d

>>> d.dtype.name

In [ ]:
a = rg.random((2, 3))
>>> a

>>> a.sum()

>>> a.min()

>>> a.max()


In [ ]:
b = np.arange(12).reshape(3, 4)
>>> b

>>>
>>> b.sum(axis=0)     # sum of each column

>>>
>>> b.min(axis=1)     # min of each row
>>>
>>> b.cumsum(axis=1)  # cumulative sum along each row


In [ ]:
a = np.arange(10)**3
>>> a
>>> a[2]

>>> a[2:5]
>>> # equivalent to a[0:6:2] = 1000;
>>> # from start to position 6, exclusive, set every 2nd element to 1000
>>> a[:6:2] = 1000
>>> a
>>> a[::-1]  # reversed a
>>> for i in a:
...     print(i**(1 / 3.))
...

In [ ]:
a = np.arange(10)**3
>>> a
>>> a[2]

>>> a[2:5]
>>> # equivalent to a[0:6:2] = 1000;
>>> # from start to position 6, exclusive, set every 2nd element to 1000
>>> a[:6:2] = 1000
>>> a
>>> a[::-1]  # reversed a
>>> for i in a:
...     print(i**(1 / 3.))
...

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

>>> def f(x, y):
...     return 10 * x + y
...
>>> b = np.fromfunction(f, (5, 4), dtype=int)
>>> b
>>> b[2, 3]
>>> b[0:5, 1]  # each row in the second column of b
>>> b[:, 1]    # equivalent to the previous example
>>> b[1:3, :]  # each column in the second and third row of b


In [ ]:
b[-1]   # the last row. Equivalent to b[-1, :]
array([40, 41, 42, 43])

In [ ]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)

>>> c.shape
>>> c[1, ...]  # same as c[1, :, :] or c[1]

>>> c[..., 2]  # same as c[:, :, 2]


In [ ]:
for row in b:
...     print(row)
...
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]

In [ ]:
for element in b.flat:
...     print(element)
...
0

Shape Manipulation