In [ ]:
########Python tutorial 3

In [2]:
# !python3 -m pip install numpy
# !python -m pip install numpy
# !py -m pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 5.3 MB/s eta 0:00:0000:0100:01
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor

In [5]:
import numpy

In [8]:
x = [25, 27, 92, 1, 40, -13, 0, 17]

In [9]:
a1 = numpy.array(x)


In [10]:
print(type(a1))


<class 'numpy.ndarray'>


In [17]:
a1

array([ 25,  27,  92,   1,  40, -13,   0,  17])

In [18]:
x*2 

[25, 27, 92, 1, 40, -13, 0, 17, 25, 27, 92, 1, 40, -13, 0, 17]

In [19]:
y = []

for i in x:
    y.append(i*2)

In [ ]:
#Check shape #a1.shape 
#Reshape #a1.reshape((4,3))
#check dimensions #a1.ndim
#find mean, standard deviation, variance, sum min, max, #a1.mean, a1.sum...
#transpose #a1.transpose()
#matrix multiplication #numpy.matmul(a1,a2)
#Array mathematical operations #a1+a2


In [20]:
y

[50, 54, 184, 2, 80, -26, 0, 34]

In [24]:
x2 = [[1,2,3],[4,5,6],[8,9,10],[9, 10, 22]]


In [29]:
a2 = numpy.array(x2)
a2
a1

array([ 25,  27,  92,   1,  40, -13,   0,  17])

In [31]:
a1.shape
a2.shape
a2.ndim
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [ 9, 10, 22]])

In [ ]:
#find mean, standard deviation, variance, sum min, max, #a1.mean, a1.sum...

In [35]:
a2.mean
a2
a2.sum
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [ 9, 10, 22]])

In [ ]:
#transpose #a1.transpose()
#matrix multiplication #numpy.matmul(a1,a2)
#Array mathematical operations #a1+a2

In [36]:
a2.transpose()

array([[ 1,  4,  8,  9],
       [ 2,  5,  9, 10],
       [ 3,  6, 10, 22]])

In [39]:
#a1 = numpy.array(x2)

#numpy.matmul(a1,a2)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [40]:
numpy.eye(4) #i dentify matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
numpy.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
numpy.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [ 9, 10, 22]])

In [46]:
a2[1:3]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [47]:
a2[0:3,2:]

array([[ 3],
       [ 6],
       [10]])

In [48]:
a2>100

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [49]:
a1.dtype

dtype('int64')

In [ ]:
hstack #horizontal stacking 
vstack #virtical stacking

In [54]:
a1 = [25,27,92,1,40,-13,0,16])

SyntaxError: unmatched ')' (23473009.py, line 1)

In [53]:
n1 = numpy.array([30,20,30,20,30,20,30,20])
#an1 = numpy.vstack((a1,n1))

In [ ]:
#hstack #numpy.hstack(a1,a2)
# vstack #numpy.vstack(a1, a2)
#numpy.eye, numpy.zeros, numpy.ones
#a1.dtypes
#conditions

In [56]:
a1
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [ 9, 10, 22]])

In [58]:
numpy.hstack((a1,a2))

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 8,  9, 10,  8,  9, 10],
       [ 9, 10, 22,  9, 10, 22]])

In [59]:
numpy.vstack((a1, a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [ 9, 10, 22],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [ 9, 10, 22]])

In [61]:
numpy.eye(1)

array([[1.]])

In [64]:
numpy.zeros(1)

array([0.])

In [67]:
numpy.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [69]:
a1.dtype

dtype('int64')

In [71]:
condition

NameError: name 'condition' is not defined

In [76]:
ar1 = numpy.arange(100)
print(ar1.reshape((5,2,10)))

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [79]:
#linspace
print(numpy.linspace(1,10,50))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
#numpy gives gives you quality mathematical processing

In [ ]:
###Pnumpy sumarry 

In [13]:
#!python3 -m pip install pandas 

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 5.0 MB/s eta 0:00:0000:0100:01
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor

In [16]:
import pandas 

In [93]:
data = {
    'name' : ['Harsh', 'Ajay', 'Antony', 'Richard', 'Russel', 'Moneesha', 'Teddy'],
    'Age'  : [12,14,15,19,20,11,16],
    'birth_year' : [2022,2021,2019,2050,1198,1989,1998]
}


In [94]:
data

{'name': ['Harsh', 'Ajay', 'Antony', 'Richard', 'Russel', 'Moneesha', 'Teddy'],
 'Age': [12, 14, 15, 19, 20, 11, 16],
 'birth_year': [2022, 2021, 2019, 2050, 1198, 1989, 1998]}

In [95]:
df = pandas.DataFrame(data)

In [96]:
print(df)

       name  Age  birth_year
0     Harsh   12        2022
1      Ajay   14        2021
2    Antony   15        2019
3   Richard   19        2050
4    Russel   20        1198
5  Moneesha   11        1989
6     Teddy   16        1998


In [101]:
df['name']

0       Harsh
1        Ajay
2      Antony
3     Richard
4      Russel
5    Moneesha
6       Teddy
Name: name, dtype: object

In [104]:
df.iloc
df

name  Age  birth_year
0     Harsh   12        2022
1      Ajay   14        2021
2    Antony   15        2019
3   Richard   19        2050
4    Russel   20        1198
5  Moneesha   11        1989
6     Teddy   16        1998

In [105]:
df.loc
df

name  Age  birth_year
0     Harsh   12        2022
1      Ajay   14        2021
2    Antony   15        2019
3   Richard   19        2050
4    Russel   20        1198
5  Moneesha   11        1989
6     Teddy   16        1998

In [111]:
df.drop([2,3,4],axis =0, inplace=True])
df

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2672212695.py, line 1)

In [113]:
df.tail

<bound method NDFrame.tail of        name  Age  birth_year
0     Harsh   12        2022
1      Ajay   14        2021
5  Moneesha   11        1989
6     Teddy   16        1998>

In [112]:
df.head

<bound method NDFrame.head of        name  Age  birth_year
0     Harsh   12        2022
1      Ajay   14        2021
5  Moneesha   11        1989
6     Teddy   16        1998>

In [114]:
df.drop

<bound method DataFrame.drop of        name  Age  birth_year
0     Harsh   12        2022
1      Ajay   14        2021
5  Moneesha   11        1989
6     Teddy   16        1998>

In [116]:
df[df['name'] == 'Teddy' ] 

name  Age  birth_year
6  Teddy   16        1998

In [120]:
df.to_csv('data.csv')

In [ ]:
df = pandas.read_csv('c:/Users/windows/Deskstop....)

In [122]:
df = pandas.read_csv('data.csv')
df.index = df['unnamed:0']
df.drop['unnamed:0'],axis=1,inplace=True

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2984870251.py, line 3)

In [ ]:
df.index = df.index.values

In [ ]:
df